### PR TITLE
pty: expose `ttyname`

### PR DESCRIPTION
**Pull request by rauchg**

### CODE REVIEW

**Comment by Gottox** [comment]
Seems reasonable, thanks for the patch!

**Comment by rauchg** [comment]
We might want to expose it as `child.ttyname` too

**Comment by rauchg** [comment]
Or just expose `child.term` ?

**Comment by rauchg** [comment]
Added it ^

**Comment by Gottox** [comment]
I believe that the term object should not be exposed to the user. Its only purpose is to exchange data needed the for initialisation from C to JS.

`master_fd` is still accessible through `child.stdout`. For `slave_fd` I see no reason why it should be accessible at all. (If there's one please tell me.)

And finally I think that neither term nor ttyname is no property of the child process (as `child` should represents the child process) but of the pty bound to the child process. Thus ttyname should be a property of `child.stdout` as it is done with the `resize()`.

I'll merge after ttyname is a property of stdout. :)

**Comment by rauchg** [comment]
+1

**Pull request merged**
